/// Flutter icons NoorIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NoorIcons
///      fonts:
///       - asset: fonts/NoorIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NoorIcons {
  NoorIcons._();

  static const String _kFontFam = 'NoorIcons';

  static const IconData leaf = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fav = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData counter = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData font_type = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData erase_counter = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData font_size = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData tashkeel = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData auto_jump = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData vibrate = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData press = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData done = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData morning_noti = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData night_noti = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData night_mode = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData light_mode = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData rate = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData email = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData system_mode = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData all = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData sunnah = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData quraan = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData myad3yah = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData ruqyah = IconData(0xe81c, fontFamily: _kFontFam);
}
